apiVersion: 1

deleteDatasources:
  - name: mysql
    orgId: 1

datasources:
  - name: mysql
    type: mysql
    access: proxy
    url: mysql:3306
    database: meshrouter
    user: meshrouter
    secureJsonData:
      password: meshtastic
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      sslMode: disable
      tlsSkipVerify: true
      timezone: UTC
      database: meshrouter
      uid: mysql_datasource
    isDefault: true
    version: 1
    editable: true