FROM grafana/grafana:latest

COPY ./provisioning /etc/grafana/provisioning
COPY ./dashboards/dashboard.yml /etc/grafana/dashboards/dashboard.yml
COPY ./dashboards/meshtastic.json /etc/grafana/dashboards/meshtastic.json